### ISSUE TITLE
Need option to use dcct soft instead of java

### ISSUE THREAD

**Issue by Karasur** [mrpsion/burst-mining-system#3]
Need option to use dcct plot,merge,mine software instead of java..

**Comment by mrpsion** [comment]
You are free to use those tools, however this miner has its own mining and plotting engine that is integrated with the UI.  I don't think it is worth breaking the platform independence of the miner to essentially become a script wrapper for another miner.

You can also plot using dcct, and mine with this at the dame time... I actually do that on linux
