### ISSUE TITLE
Ploting address shows negative address

### ISSUE THREAD

**Issue by grasberg** [mrpsion/burst-mining-system#5]
When creating a plot the Address shows negative number.

Address
-7302191857176382859
![image](https://cloud.githubusercontent.com/assets/8834843/4338374/9ced0078-4018-11e4-8c6d-aa173c746902.png)

**Comment by mrpsion** [comment]
whats the filename for that plot?

**Comment by grasberg** [comment]
mining-system-1.20.jar

Using it on windows 7, 64Bit

**Comment by mrpsion** [comment]
no the actual file name of the plot itself in the /plots folder

**Comment by grasberg** [comment]
oh sorry, not sure, I deleted it

**Comment by grasberg** [comment]
I created a new one
The filename is:
11144552216533168757_0_2000_200

![image](https://cloud.githubusercontent.com/assets/8834843/4341203/6cde7100-4036-11e4-84be-b610ca091d6e.png)

**Comment by grasberg** [comment]
could it be that my account id is very high? 11144552216533168757

**Comment by mrpsion** [comment]
okay thats what i was looking for the account id... which is your address. thats enough for me to test.  thanks!

**Comment by mrpsion** [comment]
Yup I can replicate this. Working on a fix

**Comment by grasberg** [comment]
great man :) looking forward to a new version

**Comment by mrpsion** [comment]
your address is somehow longer than the longest possible Long value, hence it is resolving as a negative long... not sure what to do here....

are you sure thats your address?  whats your burst address... i.e. the "BURST-XXXX-XXXX-XXXX-XXXX" one?

**Comment by mrpsion** [comment]
Okay looks like the address is actually fine... I am guessing you were using the official pool, as it looks like I didnt convert the long value back to a string property when submitting shares to the offical pool... so there is a bug there. other than that ill also change the UI to display the converted back to a string version of the address, rather than the raw long to remove any confusion

**Comment by mrpsion** [comment]
Okay its fixed. So submitting shares to the Official pool shouldn't get you banned any more, and the UI should display the correct string representation of the address.  Ill try and get another release out this evening, I have a bunch of code to clean up before checking it.

**Comment by mrpsion** [comment]
Okay, just pushed a new release especially for you :) 1.21.  Download that and let me know if you are still having issues.

**Comment by grasberg** [comment]
Working fine now, thanks.
